export const getDomRefs = () => ({
  tabs: Array.from(document.querySelectorAll<HTMLButtonElement>(".tab[data-tab]")),
  issuesTab: document.getElementById("issues-tab"),
  miniOutline: document.getElementById("mini-outline"),
  editorTitle: document.getElementById("editor-title"),
  editorDesc: document.getElementById("editor-desc"),
  editorHint: document.getElementById("editor-hint"),
  editorHost: document.getElementById("editor"),
  editorViewer: document.getElementById("editor-viewer"),
  editorViewerImage: document.getElementById("editor-viewer-image") as HTMLImageElement | null,
  editorViewerPdf: document.getElementById("editor-viewer-pdf") as HTMLIFrameElement | null,
  editorViewerMessage: document.getElementById("editor-viewer-message"),
  quickInsertButton: document.getElementById("quick-insert-button"),
  quickInsertPanel: document.getElementById("quick-insert"),
  quickInsertTargetLabel: document.getElementById("quick-target"),
  quickInsertInput: document.getElementById("quick-input"),
  quickInsertHint: document.getElementById("quick-hint"),
  quickInsertAccept: document.getElementById("quick-accept"),
  quickInsertCancel: document.getElementById("quick-cancel"),
  formatButton: document.getElementById("format-button"),
  buildButton: document.getElementById("build-button"),
  synctexButton: document.getElementById("synctex-button"),
  buildTarget: document.getElementById("build-target"),
  issuesCount: document.getElementById("issues-count"),
  issuesHint: document.getElementById("issues-hint"),
  issuesBar: document.getElementById("issues-bar"),
  issuesList: document.getElementById("issues-list"),
  issuesEmpty: document.getElementById("issues-empty"),
  issuesLog: document.getElementById("issues-log"),
  issuesLogContent: document.getElementById("issues-log-content"),
  breadcrumbs: document.getElementById("breadcrumbs"),
  editorTabs: document.getElementById("editor-tabs"),
  editorTabsList: document.getElementById("editor-tabs-list"),
  launcher: document.getElementById("launcher"),
  launcherCreateButton: document.getElementById("launcher-create"),
  launcherOpenButton: document.getElementById("launcher-open"),
  launcherStatus: document.getElementById("launcher-status"),
  launcherStatusText: document.getElementById("launcher-status-text"),
  launcherStatusSpinner: document.getElementById("launcher-status-spinner"),
  launcherTemplateButtons: Array.from(
    document.querySelectorAll<HTMLButtonElement>(".launcher-template-button")
  ),
  sidebarPanels: Array.from(
    document.querySelectorAll<HTMLElement>(".panel[data-panel]")
  ),
  sidebar: document.querySelector<HTMLElement>(".sidebar"),
  sidebarPanel: document.querySelector<HTMLElement>(".sidebar-panel"),
  outlineEmpty: document.getElementById("outline-empty"),
  outlineSections: document.getElementById("outline-sections"),
  outlineTodos: document.getElementById("outline-todos"),
  outlineLabels: document.getElementById("outline-labels"),
  outlineCitations: document.getElementById("outline-citations"),
  workspaceLabel: document.getElementById("workspace-label"),
  fileTree: document.getElementById("file-tree"),
  saveFileButton: document.getElementById("save-file-button"),
  blockToggleButtons: Array.from(
    document.querySelectorAll<HTMLButtonElement>(".block-toggle-button")
  ),
  blockForms: Array.from(document.querySelectorAll<HTMLElement>(".block-form")),
  blockMathInputContainer: document.getElementById("block-math-input-container"),
  blockMathPreviewWrap: document.getElementById("block-math-preview-wrap"),
  blockMathPreview: document.getElementById("block-math-preview"),
  blockTableRows: document.getElementById("block-table-rows"),
  blockTableCols: document.getElementById("block-table-cols"),
  blockTableGrid: document.getElementById("block-table-grid"),
  blockTableRaw: document.getElementById("block-table-raw"),
  blockTableRawInput: document.getElementById("block-table-raw-input"),
  blockInsertButton: document.getElementById("block-insert-button"),
  blocksPanelBody: document.querySelector<HTMLElement>(".blocks-panel"),
  diffModal: document.getElementById("diff-modal"),
  diffTitle: document.getElementById("diff-modal-title"),
  diffModalCancel: document.getElementById("diff-modal-cancel"),
  diffModalSubmit: document.getElementById("diff-modal-submit"),
  blockDiffContainer: document.getElementById("block-diff-container"),
  diffSummary: document.getElementById("diff-summary"),
  diffFileName: document.getElementById("diff-file-name"),
  mathKeyboardDock: document.getElementById("math-keyboard-dock"),
  mathKeyboardGrid: document.getElementById("math-keyboard-grid"),
  mathKeyboardFixedGrid: document.getElementById("math-keyboard-fixed-grid"),
  mathKeyboardShiftButton: document.getElementById("math-keyboard-shift"),
  mathKeyboardTabs: Array.from(
    document.querySelectorAll<HTMLButtonElement>(".math-keyboard-tab")
  ),
  searchInput: document.getElementById("search-input"),
  searchButton: document.getElementById("search-button"),
  searchResults: document.getElementById("search-results"),
  gitStatus: document.getElementById("git-status"),
  gitRefreshButton: document.getElementById("git-refresh"),
  settingsRootSelect: document.getElementById("settings-root-select"),
  settingsRootAuto: document.getElementById("settings-root-auto"),
  settingsWorkspace: document.getElementById("settings-workspace"),
  settingsPanel: document.getElementById("settings-panel"),
  settingsNav: document.getElementById("settings-nav"),
  settingsNavItems: Array.from(
    document.querySelectorAll<HTMLButtonElement>(".settings-nav-item")
  ),
  settingsPages: document.getElementById("settings-pages"),
  settingsPageItems: Array.from(document.querySelectorAll<HTMLElement>(".settings-page")),
  settingsBackButtons: Array.from(
    document.querySelectorAll<HTMLButtonElement>(".settings-back")
  ),
  editorAlignEnvToggle: document.getElementById("editor-align-env"),
  editorFormatIndentSelect: document.getElementById("editor-format-indent"),
  editorFormatBeginEndToggle: document.getElementById("editor-format-begin-end"),
  editorFormatDocumentNoIndentToggle: document.getElementById("editor-format-document-noindent"),
  editorFormatAlignMathToggle: document.getElementById("editor-format-align-math"),
  editorFormatAlignTableToggle: document.getElementById("editor-format-align-table"),
  editorFormatBlankLinesSelect: document.getElementById("editor-format-blank-lines"),
  editorFormatVerbatimInput: document.getElementById("editor-format-verbatim-input"),
  editorFormatVerbatimAdd: document.getElementById("editor-format-verbatim-add"),
  editorFormatVerbatimHint: document.getElementById("editor-format-verbatim-hint"),
  editorFormatVerbatimList: document.getElementById("editor-format-verbatim-list"),
  editorAutoSynctexBuildToggle: document.getElementById("editor-auto-synctex-build"),
  editorPdfWindowToggle: document.getElementById("editor-pdf-window"),
  settingsCompileEngineSelect: document.getElementById("settings-compile-engine"),
  settingsEnvRefresh: document.getElementById("settings-env-refresh"),
  envRegistryInput: document.getElementById("env-registry-input"),
  envRegistryKind: document.getElementById("env-registry-kind"),
  envRegistryAdd: document.getElementById("env-registry-add"),
  envRegistryHint: document.getElementById("env-registry-hint"),
  envRegistryMathList: document.getElementById("env-registry-math"),
  envRegistryTableList: document.getElementById("env-registry-table"),
  createModal: document.getElementById("create-modal"),
  createModalTitle: document.getElementById("create-modal-title"),
  createModalSubtitle: document.getElementById("create-modal-subtitle"),
  createModalParent: document.getElementById("create-modal-parent"),
  createModalLabel: document.getElementById("create-modal-label"),
  createModalInput: document.getElementById("create-modal-input"),
  createModalHelp: document.getElementById("create-modal-help"),
  createModalCancel: document.getElementById("create-modal-cancel"),
  createModalSubmit: document.getElementById("create-modal-submit"),
  renameModal: document.getElementById("rename-modal"),
  renameModalTitle: document.getElementById("rename-modal-title"),
  renameModalTarget: document.getElementById("rename-modal-target"),
  renameModalInput: document.getElementById("rename-modal-input"),
  renameModalHelp: document.getElementById("rename-modal-help"),
  renameModalCancel: document.getElementById("rename-modal-cancel"),
  renameModalSubmit: document.getElementById("rename-modal-submit"),
  contextMenu: document.getElementById("context-menu"),
  contextMenuPanel: document.getElementById("context-menu-panel"),
});

export type DomRefs = ReturnType<typeof getDomRefs>;
