export const getDomRefs = () => ({
  tabs: Array.from(document.querySelectorAll<HTMLButtonElement>(".tab[data-tab]")),
  issuesTab: document.getElementById("issues-tab"),
  editorGroups: document.getElementById("editor-groups"),
  editorHost: document.getElementById("editor"),
  editorViewer: document.getElementById("editor-viewer"),
  editorViewerImage: document.getElementById("editor-viewer-image") as HTMLImageElement | null,
  editorViewerPdf: document.getElementById("editor-viewer-pdf") as HTMLIFrameElement | null,
  editorViewerMessage: document.getElementById("editor-viewer-message"),
  editorHostSecondary: document.getElementById("editor-secondary"),
  editorViewerSecondary: document.getElementById("editor-viewer-secondary"),
  editorViewerImageSecondary: document.getElementById(
    "editor-viewer-image-secondary"
  ) as HTMLImageElement | null,
  editorViewerPdfSecondary: document.getElementById(
    "editor-viewer-pdf-secondary"
  ) as HTMLIFrameElement | null,
  editorViewerMessageSecondary: document.getElementById("editor-viewer-message-secondary"),
  editorFallbackSecondary: document.getElementById("editor-fallback-secondary"),
  formatButton: document.getElementById("format-button"),
  partialBuildButton: document.getElementById("partial-build-button"),
  buildButton: document.getElementById("build-button"),
  synctexButton: document.getElementById("synctex-button"),
  issuesList: document.getElementById("issues-list"),
  issuesEmpty: document.getElementById("issues-empty"),
  issuesLog: document.getElementById("issues-log"),
  issuesLogContent: document.getElementById("issues-log-content"),
  editorTabs: document.getElementById("editor-tabs"),
  editorTabsList: document.getElementById("editor-tabs-list"),
  editorTabsSecondary: document.getElementById("editor-tabs-secondary"),
  editorTabsListSecondary: document.getElementById("editor-tabs-list-secondary"),
  editorSplitButton: document.getElementById("editor-split-button"),
  launcher: document.getElementById("launcher"),
  launcherCreateButton: document.getElementById("launcher-create"),
  launcherOpenButton: document.getElementById("launcher-open"),
  launcherStatus: document.getElementById("launcher-status"),
  launcherStatusText: document.getElementById("launcher-status-text"),
  launcherStatusSpinner: document.getElementById("launcher-status-spinner"),
  launcherTemplateButtons: Array.from(
    document.querySelectorAll<HTMLButtonElement>(".launcher-template-button")
  ),
  sidebarPanels: Array.from(
    document.querySelectorAll<HTMLElement>(".panel[data-panel]")
  ),
  sidebar: document.querySelector<HTMLElement>(".sidebar"),
  sidebarPanel: document.querySelector<HTMLElement>(".sidebar-panel"),
  outlineEmpty: document.getElementById("outline-empty"),
  outlineSections: document.getElementById("outline-sections"),
  outlineTodos: document.getElementById("outline-todos"),
  outlineLabels: document.getElementById("outline-labels"),
  outlineCitations: document.getElementById("outline-citations"),
  workspaceLabel: document.getElementById("workspace-label"),
  fileTree: document.getElementById("file-tree"),
  saveFileButton: document.getElementById("save-file-button"),
  blockToggleButtons: Array.from(
    document.querySelectorAll<HTMLButtonElement>(".block-toggle-button")
  ),
  blockForms: Array.from(document.querySelectorAll<HTMLElement>(".block-form")),
  blockMathInputContainer: document.getElementById("block-math-input-container"),
  blockMathPreviewWrap: document.getElementById("block-math-preview-wrap"),
  blockMathPreview: document.getElementById("block-math-preview"),
  blockTableRows: document.getElementById("block-table-rows"),
  blockTableCols: document.getElementById("block-table-cols"),
  blockTableGrid: document.getElementById("block-table-grid"),
  blockTableRaw: document.getElementById("block-table-raw"),
  blockTableRawInput: document.getElementById("block-table-raw-input"),
  blockSettingsButton: document.getElementById("block-settings-button"),
  blockCaptureButton: document.getElementById("block-capture-button"),
  blockSettingsModal: document.getElementById("block-settings-modal"),
  blockSettingsClose: document.getElementById("block-settings-close"),
  blockSettingsBack: document.getElementById("block-settings-back"),
  blockSettingsPages: Array.from(
    document.querySelectorAll<HTMLElement>(".block-settings-page[data-block-settings-page]")
  ),
  blockSettingsMenuItems: Array.from(
    document.querySelectorAll<HTMLButtonElement>(".block-settings-item[data-block-settings-target]")
  ),
  blockSettingsInlineOptions: Array.from(
    document.querySelectorAll<HTMLButtonElement>("[data-inline-format]")
  ),
  blockSettingsDisplayOptions: Array.from(
    document.querySelectorAll<HTMLButtonElement>("[data-display-format]")
  ),
  blockFormatButton: document.getElementById("block-format-button"),
  blockFormatMenu: document.getElementById("block-format-menu"),
  blockFormatOptions: Array.from(
    document.querySelectorAll<HTMLButtonElement>(".block-format-option")
  ),
  blockModeToggle: document.getElementById("block-mode-toggle"),
  blockInsertButton: document.getElementById("block-insert-button"),
  blocksPanelBody: document.querySelector<HTMLElement>(".blocks-panel"),
  diffModal: document.getElementById("diff-modal"),
  diffTitle: document.getElementById("diff-modal-title"),
  diffModalCancel: document.getElementById("diff-modal-cancel"),
  diffModalSubmit: document.getElementById("diff-modal-submit"),
  blockDiffContainer: document.getElementById("block-diff-container"),
  diffSummary: document.getElementById("diff-summary"),
  diffFileName: document.getElementById("diff-file-name"),
  mathKeyboardDock: document.getElementById("math-keyboard-dock"),
  mathKeyboardGrid: document.getElementById("math-keyboard-grid"),
  mathKeyboardFixedGrid: document.getElementById("math-keyboard-fixed-grid"),
  mathKeyboardShiftButton: document.getElementById("math-keyboard-shift"),
  mathKeyboardTabs: Array.from(
    document.querySelectorAll<HTMLButtonElement>(".math-keyboard-tab")
  ),
  searchInput: document.getElementById("search-input"),
  searchButton: document.getElementById("search-button"),
  searchResults: document.getElementById("search-results"),
  searchRename: document.getElementById("search-rename"),
  searchRenameFrom: document.getElementById("search-rename-from"),
  searchRenameTo: document.getElementById("search-rename-to"),
  searchRenameLabel: document.getElementById("search-rename-label"),
  searchRenameCite: document.getElementById("search-rename-cite"),
  searchRenameRun: document.getElementById("search-rename-run"),
  searchRenameOpenAi: document.getElementById("search-rename-open-ai"),
  searchRenameStatus: document.getElementById("search-rename-status"),
  settingsRootSelect: document.getElementById("settings-root-select"),
  settingsRootAuto: document.getElementById("settings-root-auto"),
  settingsWorkspace: document.getElementById("settings-workspace"),
  settingsPanel: document.getElementById("settings-panel"),
  settingsNav: document.getElementById("settings-nav"),
  settingsNavItems: Array.from(
    document.querySelectorAll<HTMLButtonElement>(".settings-nav-item")
  ),
  settingsPages: document.getElementById("settings-pages"),
  settingsPageItems: Array.from(document.querySelectorAll<HTMLElement>(".settings-page")),
  settingsBackButtons: Array.from(
    document.querySelectorAll<HTMLButtonElement>(".settings-back")
  ),
  editorAlignEnvToggle: document.getElementById("editor-align-env"),
  editorFormatIndentSelect: document.getElementById("editor-format-indent"),
  editorFormatBeginEndToggle: document.getElementById("editor-format-begin-end"),
  editorFormatDocumentNoIndentToggle: document.getElementById("editor-format-document-noindent"),
  editorFormatAlignMathToggle: document.getElementById("editor-format-align-math"),
  editorFormatAlignTableToggle: document.getElementById("editor-format-align-table"),
  editorFormatBlankLinesSelect: document.getElementById("editor-format-blank-lines"),
  editorFormatVerbatimInput: document.getElementById("editor-format-verbatim-input"),
  editorFormatVerbatimAdd: document.getElementById("editor-format-verbatim-add"),
  editorFormatVerbatimHint: document.getElementById("editor-format-verbatim-hint"),
  editorFormatVerbatimList: document.getElementById("editor-format-verbatim-list"),
  editorAutoSynctexBuildToggle: document.getElementById("editor-auto-synctex-build"),
  editorPdfWindowToggle: document.getElementById("editor-pdf-window"),
  settingsCompileEngineSelect: document.getElementById("settings-compile-engine"),
  settingsEnvRefresh: document.getElementById("settings-env-refresh"),
  envRegistryInput: document.getElementById("env-registry-input"),
  envRegistryKind: document.getElementById("env-registry-kind"),
  envRegistryAdd: document.getElementById("env-registry-add"),
  envRegistryHint: document.getElementById("env-registry-hint"),
  envRegistryMathList: document.getElementById("env-registry-math"),
  envRegistryTableList: document.getElementById("env-registry-table"),
  createModal: document.getElementById("create-modal"),
  createModalTitle: document.getElementById("create-modal-title"),
  createModalSubtitle: document.getElementById("create-modal-subtitle"),
  createModalParent: document.getElementById("create-modal-parent"),
  createModalLabel: document.getElementById("create-modal-label"),
  createModalInput: document.getElementById("create-modal-input"),
  createModalHelp: document.getElementById("create-modal-help"),
  createModalCancel: document.getElementById("create-modal-cancel"),
  createModalSubmit: document.getElementById("create-modal-submit"),
  renameModal: document.getElementById("rename-modal"),
  renameModalTitle: document.getElementById("rename-modal-title"),
  renameModalTarget: document.getElementById("rename-modal-target"),
  renameModalInput: document.getElementById("rename-modal-input"),
  renameModalHelp: document.getElementById("rename-modal-help"),
  renameModalCancel: document.getElementById("rename-modal-cancel"),
  renameModalSubmit: document.getElementById("rename-modal-submit"),
  contextMenu: document.getElementById("context-menu"),
  contextMenuPanel: document.getElementById("context-menu-panel"),
  alchemyPanel: document.getElementById("alchemy-panel"),
  alchemySettingsButton: document.getElementById("alchemy-settings-button"),
  alchemySettings: document.getElementById("alchemy-settings"),
  alchemyCaptureButton: document.getElementById("alchemy-capture-button"),
  alchemyStatusLine: document.getElementById("alchemy-status-line"),
  alchemyOcrLanguage: document.getElementById("alchemy-ocr-language"),
  aiPanel: document.getElementById("ai-panel"),
  aiChat: document.getElementById("ai-chat"),
  aiChatLog: document.getElementById("ai-chat-log"),
  aiProposals: document.getElementById("ai-proposals"),
  aiInput: document.getElementById("ai-input"),
  aiSend: document.getElementById("ai-send"),
  aiStatus: document.getElementById("ai-status"),
  aiClear: document.getElementById("ai-clear"),
  aiChatList: document.getElementById("ai-chat-list"),
  aiChatNew: document.getElementById("ai-chat-new"),
  captureWindowModal: document.getElementById("capture-window-modal"),
  captureWindowCancel: document.getElementById("capture-window-cancel"),
  captureWindowSearch: document.getElementById("capture-window-search"),
  captureWindowGrid: document.getElementById("capture-window-grid"),
  captureWindowItemTemplate: document.getElementById("capture-window-item-template"),
  captureCropModal: document.getElementById("capture-crop-modal"),
  captureCropRetry: document.getElementById("capture-crop-retry"),
  captureCropCancel: document.getElementById("capture-crop-cancel"),
  captureCropApply: document.getElementById("capture-crop-apply"),
  captureCropCanvas: document.getElementById("capture-crop-canvas"),
  captureCropImage: document.getElementById("capture-crop-image"),
  captureCropSelection: document.getElementById("capture-crop-selection"),
  captureCropGuide: document.getElementById("capture-crop-guide"),
  captureCropSize: document.getElementById("capture-crop-size"),
  captureCropHint: document.getElementById("capture-crop-hint"),
  mathCaptureWindowModal: document.getElementById("math-capture-window-modal"),
  mathCaptureWindowCancel: document.getElementById("math-capture-window-cancel"),
  mathCaptureWindowSearch: document.getElementById("math-capture-window-search"),
  mathCaptureWindowGrid: document.getElementById("math-capture-window-grid"),
  mathCaptureWindowItemTemplate: document.getElementById("math-capture-window-item-template"),
  mathCaptureCropModal: document.getElementById("math-capture-crop-modal"),
  mathCaptureCropRetry: document.getElementById("math-capture-crop-retry"),
  mathCaptureCropCancel: document.getElementById("math-capture-crop-cancel"),
  mathCaptureCropApply: document.getElementById("math-capture-crop-apply"),
  mathCaptureCropCanvas: document.getElementById("math-capture-crop-canvas"),
  mathCaptureCropImage: document.getElementById("math-capture-crop-image"),
  mathCaptureCropSelection: document.getElementById("math-capture-crop-selection"),
  mathCaptureCropGuide: document.getElementById("math-capture-crop-guide"),
  mathCaptureCropSize: document.getElementById("math-capture-crop-size"),
  mathCaptureCropHint: document.getElementById("math-capture-crop-hint"),
});

export type DomRefs = ReturnType<typeof getDomRefs>;
