import type { MathKey, MathKeyboardTab } from "./types.js";

export const mathKeyboardFixedKeys: MathKey[] = [
  { label: "+", latex: "+", shiftLabel: "⊕", shiftLatex: "\\oplus " },
  { label: "−", latex: "-", shiftLabel: "⊖", shiftLatex: "\\ominus " },
  { label: "×", latex: "\\times ", shiftLabel: "⊗", shiftLatex: "\\otimes " },
  { label: "÷", latex: "\\div ", shiftLabel: "⊘", shiftLatex: "\\oslash " },
  { label: "·", latex: "\\cdot ", shiftLabel: "•", shiftLatex: "\\bullet " },
  { label: "=", latex: "=", shiftLabel: "≡", shiftLatex: "\\equiv " },
  { label: "&", latex: "&" },
  { label: "\\\\", latex: "\\\\" },
  { label: "≠", latex: "\\neq ", shiftLabel: "≈", shiftLatex: "\\approx " },
  { label: "≤", latex: "\\leq ", shiftLabel: "≦", shiftLatex: "\\leqq " },
  { label: "≥", latex: "\\geq ", shiftLabel: "≧", shiftLatex: "\\geqq " },
  { label: "<", latex: "<", shiftLabel: "≪", shiftLatex: "\\ll " },
  { label: ">", latex: ">", shiftLabel: "≫", shiftLatex: "\\gg " },
  { label: "±", latex: "\\pm ", shiftLabel: "∓", shiftLatex: "\\mp " },
  {
    label: "sum",
    latex: "\\sum ",
    shiftLabel: "prod",
    shiftLatex: "\\prod ",
    displayLatex: "\\sum",
    shiftDisplayLatex: "\\prod",
  },
  {
    label: "int",
    latex: "\\int ",
    shiftLabel: "int_ab",
    shiftLatex: "\\int_{#?}^{#?}",
    shiftFallback: "\\int_{}^{}",
    displayLatex: "\\int",
    shiftDisplayLatex: "\\int_{a}^{b}",
  },
  {
    label: "∞",
    latex: "\\infty ",
    shiftLabel: "ℵ0",
    shiftLatex: "\\aleph_0 ",
    displayLatex: "\\infty",
    shiftDisplayLatex: "\\aleph_0",
  },
  {
    label: "sqrt",
    latex: "\\sqrt{#?}",
    fallback: "\\sqrt{}",
    shiftLabel: "root",
    shiftLatex: "\\sqrt[#?]{#?}",
    shiftFallback: "\\sqrt[]{}",
    displayLatex: "\\sqrt{x}",
    shiftDisplayLatex: "\\sqrt[n]{x}",
  },
  {
    label: "frac",
    latex: "\\frac{#?}{#?}",
    fallback: "\\frac{}{}",
    shiftLabel: "dfrac",
    shiftLatex: "\\dfrac{#?}{#?}",
    shiftFallback: "\\dfrac{}{}",
    displayLatex: "\\frac{a}{b}",
    shiftDisplayLatex: "\\dfrac{a}{b}",
  },
  {
    label: "pow",
    latex: "^{#?}",
    fallback: "^{}",
    shiftLabel: "x^2",
    shiftLatex: "^{2}",
    displayLatex: "x^{n}",
    shiftDisplayLatex: "x^{2}",
  },
  {
    label: "sub",
    latex: "_{#?}",
    fallback: "_{}",
    shiftLabel: "x_0",
    shiftLatex: "_{0}",
    displayLatex: "x_{n}",
    shiftDisplayLatex: "x_{0}",
  },
  {
    label: "abs",
    latex: "\\left|#?\\right|",
    fallback: "\\left|\\right|",
    shiftLabel: "inner",
    shiftLatex: "\\left\\langle#?\\right\\rangle",
    shiftFallback: "\\left\\langle\\right\\rangle",
    displayLatex: "\\left|x\\right|",
    shiftDisplayLatex: "\\langle x, y \\rangle",
  },
  {
    label: "sin",
    latex: "\\sin ",
    shiftLabel: "arcsin",
    shiftLatex: "\\arcsin ",
    displayLatex: "\\sin",
    shiftDisplayLatex: "\\arcsin",
  },
  {
    label: "cos",
    latex: "\\cos ",
    shiftLabel: "arccos",
    shiftLatex: "\\arccos ",
    displayLatex: "\\cos",
    shiftDisplayLatex: "\\arccos",
  },
  {
    label: "tan",
    latex: "\\tan ",
    shiftLabel: "arctan",
    shiftLatex: "\\arctan ",
    displayLatex: "\\tan",
    shiftDisplayLatex: "\\arctan",
  },
  {
    label: "log",
    latex: "\\log ",
    shiftLabel: "log_b",
    shiftLatex: "\\log_{#?}",
    shiftFallback: "\\log_{}",
    displayLatex: "\\log",
    shiftDisplayLatex: "\\log_{b}",
  },
  {
    label: "ln",
    latex: "\\ln ",
    shiftLabel: "lg",
    shiftLatex: "\\lg ",
    displayLatex: "\\ln",
    shiftDisplayLatex: "\\lg",
  },
  {
    label: "exp",
    latex: "\\exp ",
    shiftLabel: "e^",
    shiftLatex: "e^{#?}",
    shiftFallback: "e^{}",
    displayLatex: "\\exp",
    shiftDisplayLatex: "e^{x}",
  },
  {
    label: "lim",
    latex: "\\lim ",
    shiftLabel: "lim→",
    shiftLatex: "\\lim_{#? \\to #?}",
    shiftFallback: "\\lim_{}",
    displayLatex: "\\lim",
    shiftDisplayLatex: "\\lim_{x \\to a}",
  },
  { label: "→", latex: "\\to ", shiftLabel: "⇒", shiftLatex: "\\Rightarrow " },
  {
    label: "∂",
    latex: "\\partial ",
    shiftLabel: "d",
    shiftLatex: "\\mathrm{d} ",
    displayLatex: "\\partial",
    shiftDisplayLatex: "\\mathrm{d}",
  },
  {
    label: "∇",
    latex: "\\nabla ",
    shiftLabel: "Δ",
    shiftLatex: "\\Delta ",
    displayLatex: "\\nabla",
    shiftDisplayLatex: "\\Delta",
  },
];

export const mathKeyboardSets: Record<MathKeyboardTab, MathKey[]> = {
  analysis: [
    {
      label: "d/dx",
      latex: "\\frac{d}{d#?}#?",
      fallback: "\\frac{d}{d} ",
      shiftLabel: "d2/dx2",
      shiftLatex: "\\frac{d^2}{d#?^2}#?",
      shiftFallback: "\\frac{d^2}{d^2} ",
      displayLatex: "\\frac{d}{dx}",
      shiftDisplayLatex: "\\frac{d^2}{dx^2}",
    },
    {
      label: "∂/∂x",
      latex: "\\frac{\\partial}{\\partial #?}#?",
      fallback: "\\frac{\\partial}{\\partial} ",
      shiftLabel: "∂2/∂x2",
      shiftLatex: "\\frac{\\partial^2}{\\partial #?^2}#?",
      shiftFallback: "\\frac{\\partial^2}{\\partial^2} ",
      displayLatex: "\\frac{\\partial}{\\partial x}",
      shiftDisplayLatex: "\\frac{\\partial^2}{\\partial x^2}",
    },
    {
      label: "∮",
      latex: "\\oint ",
      shiftLabel: "∮_C",
      shiftLatex: "\\oint_{#?}",
      shiftFallback: "\\oint_{}",
      displayLatex: "\\oint",
      shiftDisplayLatex: "\\oint_{C}",
    },
    {
      label: "∬",
      latex: "\\iint ",
      shiftLabel: "∭",
      shiftLatex: "\\iiint ",
      displayLatex: "\\iint",
      shiftDisplayLatex: "\\iiint",
    },
    {
      label: "lim sup",
      latex: "\\limsup ",
      shiftLabel: "lim inf",
      shiftLatex: "\\liminf ",
      displayLatex: "\\limsup",
      shiftDisplayLatex: "\\liminf",
    },
    {
      label: "sup",
      latex: "\\sup ",
      shiftLabel: "inf",
      shiftLatex: "\\inf ",
      displayLatex: "\\sup",
      shiftDisplayLatex: "\\inf",
    },
    {
      label: "max",
      latex: "\\max ",
      shiftLabel: "min",
      shiftLatex: "\\min ",
      displayLatex: "\\max",
      shiftDisplayLatex: "\\min",
    },
    {
      label: "≈",
      latex: "\\approx ",
      shiftLabel: "∼",
      shiftLatex: "\\sim ",
      displayLatex: "\\approx",
      shiftDisplayLatex: "\\sim",
    },
    {
      label: "≃",
      latex: "\\simeq ",
      shiftLabel: "≅",
      shiftLatex: "\\cong ",
      displayLatex: "\\simeq",
      shiftDisplayLatex: "\\cong",
    },
    {
      label: "O",
      latex: "\\mathcal{O} ",
      shiftLabel: "o",
      shiftLatex: "\\mathrm{o} ",
      displayLatex: "\\mathcal{O}",
      shiftDisplayLatex: "\\mathrm{o}",
    },
    {
      label: "ℒ",
      latex: "\\mathcal{L} ",
      shiftLabel: "ℓ",
      shiftLatex: "\\ell ",
      displayLatex: "\\mathcal{L}",
      shiftDisplayLatex: "\\ell",
    },
    {
      label: "⟨ ⟩",
      latex: "\\left\\langle#?\\right\\rangle",
      fallback: "\\left\\langle\\right\\rangle",
      shiftLabel: "⟨⟩_n",
      shiftLatex: "\\left\\langle#?\\right\\rangle_{#?}",
      shiftFallback: "\\left\\langle\\right\\rangle_{}",
      displayLatex: "\\langle x \\rangle",
      shiftDisplayLatex: "\\langle x \\rangle_{n}",
    },
    {
      label: "∫_a^b",
      latex: "\\int_{#?}^{#?}",
      shiftLabel: "∫_C",
      shiftLatex: "\\int_{#?}",
      shiftFallback: "\\int_{}",
      displayLatex: "\\int_{a}^{b}",
      shiftDisplayLatex: "\\int_{C}",
    },
    {
      label: "→∞",
      latex: "\\to \\infty ",
      shiftLabel: "→0",
      shiftLatex: "\\to 0 ",
      displayLatex: "\\to \\infty",
      shiftDisplayLatex: "\\to 0",
    },
    {
      label: "∑",
      latex: "\\sum_{#?}^{#?}",
      shiftLabel: "∏",
      shiftLatex: "\\prod_{#?}^{#?}",
      shiftFallback: "\\prod_{}^{}",
      displayLatex: "\\sum_{i=1}^{n}",
      shiftDisplayLatex: "\\prod_{i=1}^{n}",
    },
    {
      label: "lim",
      latex: "\\lim_{#? \\to #?}",
      shiftLabel: "limsup",
      shiftLatex: "\\limsup_{#?}",
      shiftFallback: "\\limsup_{}",
      displayLatex: "\\lim_{x \\to 0}",
      shiftDisplayLatex: "\\limsup_{n}",
    },
    {
      label: "∂",
      latex: "\\partial ",
      shiftLabel: "∇",
      shiftLatex: "\\nabla ",
      displayLatex: "\\partial",
      shiftDisplayLatex: "\\nabla",
    },
  ],
  algebra: [
    {
      label: "√",
      latex: "\\sqrt{#?}",
      fallback: "\\sqrt{}",
      shiftLabel: "∛",
      shiftLatex: "\\sqrt[3]{#?}",
      shiftFallback: "\\sqrt[3]{}",
      displayLatex: "\\sqrt{x}",
      shiftDisplayLatex: "\\sqrt[3]{x}",
    },
    {
      label: "√n",
      latex: "\\sqrt[#?]{#?}",
      fallback: "\\sqrt[]{}",
      shiftLabel: "x^y",
      shiftLatex: "{#?}^{#?}",
      shiftFallback: "{}^{}",
      displayLatex: "\\sqrt[n]{x}",
      shiftDisplayLatex: "x^{y}",
    },
    {
      label: "x^2",
      latex: "^{2}",
      shiftLabel: "x^n",
      shiftLatex: "^{#?}",
      shiftFallback: "^{}",
      displayLatex: "x^{2}",
      shiftDisplayLatex: "x^{n}",
    },
    {
      label: "x_0",
      latex: "_{0}",
      shiftLabel: "x_n",
      shiftLatex: "_{#?}",
      shiftFallback: "_{}",
      displayLatex: "x_{0}",
      shiftDisplayLatex: "x_{n}",
    },
    {
      label: "|x|",
      latex: "\\left|#?\\right|",
      fallback: "\\left|\\right|",
      shiftLabel: "||x||",
      shiftLatex: "\\left\\lVert#?\\right\\rVert",
      shiftFallback: "\\left\\lVert\\right\\rVert",
      displayLatex: "\\left|x\\right|",
      shiftDisplayLatex: "\\left\\lVert x\\right\\rVert",
    },
    {
      label: "⟨x,y⟩",
      latex: "\\left\\langle#?\\right\\rangle",
      fallback: "\\left\\langle\\right\\rangle",
      shiftLabel: "·",
      shiftLatex: "\\cdot ",
      displayLatex: "\\langle x, y \\rangle",
      shiftDisplayLatex: "\\cdot",
    },
    {
      label: "a/b",
      latex: "\\frac{#?}{#?}",
      fallback: "\\frac{}{}",
      shiftLabel: "dfrac",
      shiftLatex: "\\dfrac{#?}{#?}",
      shiftFallback: "\\dfrac{}{}",
      displayLatex: "\\frac{a}{b}",
      shiftDisplayLatex: "\\dfrac{a}{b}",
    },
    {
      label: "( )",
      latex: "\\left(#?\\right)",
      fallback: "\\left(\\right)",
      shiftLabel: "[ ]",
      shiftLatex: "\\left[#?\\right]",
      shiftFallback: "\\left[\\right]",
      displayLatex: "(x)",
      shiftDisplayLatex: "[x]",
    },
    {
      label: "{ }",
      latex: "\\left\\{#?\\right\\}",
      fallback: "\\left\\{\\right\\}",
      shiftLabel: "⟨ ⟩",
      shiftLatex: "\\left\\langle#?\\right\\rangle",
      shiftFallback: "\\left\\langle\\right\\rangle",
      displayLatex: "\\{x\\}",
      shiftDisplayLatex: "\\langle x \\rangle",
    },
    {
      label: "x≠0",
      latex: "#? \\neq 0",
      shiftLabel: "x=0",
      shiftLatex: "#? = 0",
      displayLatex: "x \\neq 0",
      shiftDisplayLatex: "x = 0",
    },
    {
      label: "x≪y",
      latex: "#? \\ll #?",
      shiftLabel: "x≫y",
      shiftLatex: "#? \\gg #?",
      displayLatex: "x \\ll y",
      shiftDisplayLatex: "x \\gg y",
    },
    {
      label: "≡",
      latex: "\\equiv ",
      shiftLabel: "≅",
      shiftLatex: "\\cong ",
      displayLatex: "\\equiv",
      shiftDisplayLatex: "\\cong",
    },
    {
      label: "∝",
      latex: "\\propto ",
      shiftLabel: "~",
      shiftLatex: "\\sim ",
      displayLatex: "\\propto",
      shiftDisplayLatex: "\\sim",
    },
    {
      label: "≈",
      latex: "\\approx ",
      shiftLabel: "≃",
      shiftLatex: "\\simeq ",
      displayLatex: "\\approx",
      shiftDisplayLatex: "\\simeq",
    },
    {
      label: "↦",
      latex: "\\mapsto ",
      shiftLabel: "→",
      shiftLatex: "\\to ",
      displayLatex: "\\mapsto",
      shiftDisplayLatex: "\\to",
    },
    {
      label: "⊂",
      latex: "\\subset ",
      shiftLabel: "⊆",
      shiftLatex: "\\subseteq ",
      displayLatex: "\\subset",
      shiftDisplayLatex: "\\subseteq",
    },
    {
      label: "⊃",
      latex: "\\supset ",
      shiftLabel: "⊇",
      shiftLatex: "\\supseteq ",
      displayLatex: "\\supset",
      shiftDisplayLatex: "\\supseteq",
    },
    {
      label: "→",
      latex: "\\to ",
      shiftLabel: "⇒",
      shiftLatex: "\\Rightarrow ",
      displayLatex: "\\to",
      shiftDisplayLatex: "\\Rightarrow",
    },
    {
      label: "⇔",
      latex: "\\Leftrightarrow ",
      shiftLabel: "↔",
      shiftLatex: "\\leftrightarrow ",
      displayLatex: "\\Leftrightarrow",
      shiftDisplayLatex: "\\leftrightarrow",
    },
  ],
  sets: [
    {
      label: "{ }",
      latex: "\\left\\{#?\\right\\}",
      fallback: "\\left\\{\\right\\}",
      shiftLabel: "( )",
      shiftLatex: "\\left(#?\\right)",
      shiftFallback: "\\left(\\right)",
      displayLatex: "\\{x\\}",
      shiftDisplayLatex: "(x)",
    },
    {
      label: "∈",
      latex: "\\in ",
      shiftLabel: "∉",
      shiftLatex: "\\notin ",
      displayLatex: "\\in",
      shiftDisplayLatex: "\\notin",
    },
    {
      label: "⊂",
      latex: "\\subset ",
      shiftLabel: "⊆",
      shiftLatex: "\\subseteq ",
      displayLatex: "\\subset",
      shiftDisplayLatex: "\\subseteq",
    },
    {
      label: "⊃",
      latex: "\\supset ",
      shiftLabel: "⊇",
      shiftLatex: "\\supseteq ",
      displayLatex: "\\supset",
      shiftDisplayLatex: "\\supseteq",
    },
    {
      label: "∩",
      latex: "\\cap ",
      shiftLabel: "∪",
      shiftLatex: "\\cup ",
      displayLatex: "\\cap",
      shiftDisplayLatex: "\\cup",
    },
    {
      label: "∅",
      latex: "\\emptyset ",
      shiftLabel: "\u2205",
      shiftLatex: "\\varnothing ",
      displayLatex: "\\emptyset",
      shiftDisplayLatex: "\\varnothing",
    },
    {
      label: "∀",
      latex: "\\forall ",
      shiftLabel: "∃",
      shiftLatex: "\\exists ",
      displayLatex: "\\forall",
      shiftDisplayLatex: "\\exists",
    },
    {
      label: "\u2115",
      latex: "\\mathbb{N} ",
      shiftLabel: "\u211a",
      shiftLatex: "\\mathbb{Z} ",
      displayLatex: "\\mathbb{N}",
      shiftDisplayLatex: "\\mathbb{Z}",
    },
    {
      label: "\u211a",
      latex: "\\mathbb{Z} ",
      shiftLabel: "\u211a_0",
      shiftLatex: "\\mathbb{Z}_{#?}",
      shiftFallback: "\\mathbb{Z}_{}",
      displayLatex: "\\mathbb{Z}",
      shiftDisplayLatex: "\\mathbb{Z}_{0}",
    },
    {
      label: "\u211a^+",
      latex: "\\mathbb{Z}^{+} ",
      shiftLabel: "\u211a^-",
      shiftLatex: "\\mathbb{Z}^{-} ",
      displayLatex: "\\mathbb{Z}^{+}",
      shiftDisplayLatex: "\\mathbb{Z}^{-}",
    },
    {
      label: "\u211d",
      latex: "\\mathbb{R} ",
      shiftLabel: "\u211d^n",
      shiftLatex: "\\mathbb{R}^{#?}",
      shiftFallback: "\\mathbb{R}^{}",
      displayLatex: "\\mathbb{R}",
      shiftDisplayLatex: "\\mathbb{R}^{n}",
    },
    {
      label: "\u2102",
      latex: "\\mathbb{C} ",
      shiftLabel: "\u2102^n",
      shiftLatex: "\\mathbb{C}^{#?}",
      shiftFallback: "\\mathbb{C}^{}",
      displayLatex: "\\mathbb{C}",
      shiftDisplayLatex: "\\mathbb{C}^{n}",
    },
    {
      label: "P(A)",
      latex: "\\mathbb{P}(#?)",
      fallback: "\\mathbb{P}()",
      shiftLabel: "E[X]",
      shiftLatex: "\\mathbb{E}[#?]",
      shiftFallback: "\\mathbb{E}[]",
      displayLatex: "\\mathbb{P}(A)",
      shiftDisplayLatex: "\\mathbb{E}[X]",
    },
    {
      label: "\u2119",
      latex: "\\mathcal{P}(#?)",
      fallback: "\\mathcal{P}()",
      shiftLabel: "\u2119(A)",
      shiftLatex: "\\mathcal{P}(#?)",
      shiftFallback: "\\mathcal{P}()",
      displayLatex: "\\mathcal{P}(A)",
      shiftDisplayLatex: "\\mathcal{P}(A)",
    },
    {
      label: "|A|",
      latex: "\\left|#?\\right|",
      fallback: "\\left|\\right|",
      shiftLabel: "\u2113(A)",
      shiftLatex: "\\ell(#?)",
      shiftFallback: "\\ell()",
      displayLatex: "|A|",
      shiftDisplayLatex: "\\ell(A)",
    },
    {
      label: "\u2211",
      latex: "\\sum_{#?}#?",
      shiftLabel: "\u2229",
      shiftLatex: "\\bigcap_{#?}#?",
      shiftFallback: "\\bigcap_{}",
      displayLatex: "\\sum_{i} x_i",
      shiftDisplayLatex: "\\bigcap_{i} A_i",
    },
    {
      label: "\u220f",
      latex: "\\prod_{#?}#?",
      shiftLabel: "\u22c3",
      shiftLatex: "\\bigcup_{#?}#?",
      shiftFallback: "\\bigcup_{}",
      displayLatex: "\\prod_{i} x_i",
      shiftDisplayLatex: "\\bigcup_{i} A_i",
    },
  ],
  logic: [
    {
      label: "⇒",
      latex: "\\Rightarrow ",
      shiftLabel: "→",
      shiftLatex: "\\to ",
      displayLatex: "\\Rightarrow",
      shiftDisplayLatex: "\\to",
    },
    {
      label: "⇔",
      latex: "\\Leftrightarrow ",
      shiftLabel: "↔",
      shiftLatex: "\\leftrightarrow ",
      displayLatex: "\\Leftrightarrow",
      shiftDisplayLatex: "\\leftrightarrow",
    },
    {
      label: "¬",
      latex: "\\neg ",
      shiftLabel: "~",
      shiftLatex: "\\sim ",
      displayLatex: "\\neg",
      shiftDisplayLatex: "\\sim",
    },
    {
      label: "∧",
      latex: "\\land ",
      shiftLabel: "∨",
      shiftLatex: "\\lor ",
      displayLatex: "\\land",
      shiftDisplayLatex: "\\lor",
    },
    {
      label: "⊕",
      latex: "\\oplus ",
      shiftLabel: "⊗",
      shiftLatex: "\\otimes ",
      displayLatex: "\\oplus",
      shiftDisplayLatex: "\\otimes",
    },
    {
      label: "∀",
      latex: "\\forall ",
      shiftLabel: "∃",
      shiftLatex: "\\exists ",
      displayLatex: "\\forall",
      shiftDisplayLatex: "\\exists",
    },
    {
      label: "∃!",
      latex: "\\exists! ",
      shiftLabel: "∃",
      shiftLatex: "\\exists ",
      displayLatex: "\\exists!",
      shiftDisplayLatex: "\\exists",
    },
    {
      label: "∴",
      latex: "\\therefore ",
      shiftLabel: "∵",
      shiftLatex: "\\because ",
      displayLatex: "\\therefore",
      shiftDisplayLatex: "\\because",
    },
    {
      label: "⊥",
      latex: "\\bot ",
      shiftLabel: "\u22a4",
      shiftLatex: "\\top ",
      displayLatex: "\\bot",
      shiftDisplayLatex: "\\top",
    },
    {
      label: "⊢",
      latex: "\\vdash ",
      shiftLabel: "⊣",
      shiftLatex: "\\dashv ",
      displayLatex: "\\vdash",
      shiftDisplayLatex: "\\dashv",
    },
    {
      label: "⊨",
      latex: "\\models ",
      shiftLabel: "⊧",
      shiftLatex: "\\vDash ",
      displayLatex: "\\models",
      shiftDisplayLatex: "\\vDash",
    },
  ],
  arrows: [
    {
      label: "→",
      latex: "\\to ",
      shiftLabel: "⇒",
      shiftLatex: "\\Rightarrow ",
      displayLatex: "\\to",
      shiftDisplayLatex: "\\Rightarrow",
    },
    {
      label: "←",
      latex: "\\leftarrow ",
      shiftLabel: "⇐",
      shiftLatex: "\\Leftarrow ",
      displayLatex: "\\leftarrow",
      shiftDisplayLatex: "\\Leftarrow",
    },
    {
      label: "↔",
      latex: "\\leftrightarrow ",
      shiftLabel: "⇔",
      shiftLatex: "\\Leftrightarrow ",
      displayLatex: "\\leftrightarrow",
      shiftDisplayLatex: "\\Leftrightarrow",
    },
    {
      label: "↦",
      latex: "\\mapsto ",
      shiftLabel: "↣",
      shiftLatex: "\\rightarrowtail ",
      displayLatex: "\\mapsto",
      shiftDisplayLatex: "\\rightarrowtail",
    },
    {
      label: "↪",
      latex: "\\hookrightarrow ",
      shiftLabel: "↩",
      shiftLatex: "\\hookleftarrow ",
      displayLatex: "\\hookrightarrow",
      shiftDisplayLatex: "\\hookleftarrow",
    },
    {
      label: "↣",
      latex: "\\rightarrowtail ",
      shiftLabel: "↢",
      shiftLatex: "\\leftarrowtail ",
      displayLatex: "\\rightarrowtail",
      shiftDisplayLatex: "\\leftarrowtail",
    },
    {
      label: "↠",
      latex: "\\twoheadrightarrow ",
      shiftLabel: "↞",
      shiftLatex: "\\twoheadleftarrow ",
      displayLatex: "\\twoheadrightarrow",
      shiftDisplayLatex: "\\twoheadleftarrow",
    },
    {
      label: "↗",
      latex: "\\nearrow ",
      shiftLabel: "↘",
      shiftLatex: "\\searrow ",
      displayLatex: "\\nearrow",
      shiftDisplayLatex: "\\searrow",
    },
    {
      label: "↙",
      latex: "\\swarrow ",
      shiftLabel: "↖",
      shiftLatex: "\\nwarrow ",
      displayLatex: "\\swarrow",
      shiftDisplayLatex: "\\nwarrow",
    },
    {
      label: "↩",
      latex: "\\hookleftarrow ",
      shiftLabel: "↪",
      shiftLatex: "\\hookrightarrow ",
      displayLatex: "\\hookleftarrow",
      shiftDisplayLatex: "\\hookrightarrow",
    },
    {
      label: "↭",
      latex: "\\leftrightsquigarrow ",
      shiftLabel: "↝",
      shiftLatex: "\\rightsquigarrow ",
      displayLatex: "\\leftrightsquigarrow",
      shiftDisplayLatex: "\\rightsquigarrow",
    },
  ],
  greek: [
    { label: "α", latex: "\\alpha ", shiftLabel: "Α", shiftLatex: "A ", displayLatex: "\\alpha", shiftDisplayLatex: "A" },
    { label: "β", latex: "\\beta ", shiftLabel: "Β", shiftLatex: "B ", displayLatex: "\\beta", shiftDisplayLatex: "B" },
    { label: "γ", latex: "\\gamma ", shiftLabel: "Γ", shiftLatex: "\\Gamma ", displayLatex: "\\gamma", shiftDisplayLatex: "\\Gamma" },
    { label: "δ", latex: "\\delta ", shiftLabel: "Δ", shiftLatex: "\\Delta ", displayLatex: "\\delta", shiftDisplayLatex: "\\Delta" },
    { label: "ε", latex: "\\epsilon ", shiftLabel: "Ε", shiftLatex: "E ", displayLatex: "\\epsilon", shiftDisplayLatex: "E" },
    { label: "ϵ", latex: "\\varepsilon ", shiftLabel: "∈", shiftLatex: "\\in ", displayLatex: "\\varepsilon", shiftDisplayLatex: "\\in" },
    { label: "ζ", latex: "\\zeta ", shiftLabel: "Ζ", shiftLatex: "Z ", displayLatex: "\\zeta", shiftDisplayLatex: "Z" },
    { label: "η", latex: "\\eta ", shiftLabel: "Η", shiftLatex: "H ", displayLatex: "\\eta", shiftDisplayLatex: "H" },
    { label: "θ", latex: "\\theta ", shiftLabel: "Θ", shiftLatex: "\\Theta ", displayLatex: "\\theta", shiftDisplayLatex: "\\Theta" },
    { label: "ϑ", latex: "\\vartheta ", shiftLabel: "Θ", shiftLatex: "\\Theta ", displayLatex: "\\vartheta", shiftDisplayLatex: "\\Theta" },
    { label: "ι", latex: "\\iota ", shiftLabel: "Ι", shiftLatex: "I ", displayLatex: "\\iota", shiftDisplayLatex: "I" },
    { label: "κ", latex: "\\kappa ", shiftLabel: "Κ", shiftLatex: "K ", displayLatex: "\\kappa", shiftDisplayLatex: "K" },
    { label: "λ", latex: "\\lambda ", shiftLabel: "Λ", shiftLatex: "\\Lambda ", displayLatex: "\\lambda", shiftDisplayLatex: "\\Lambda" },
    { label: "μ", latex: "\\mu ", shiftLabel: "Μ", shiftLatex: "M ", displayLatex: "\\mu", shiftDisplayLatex: "M" },
    { label: "ν", latex: "\\nu ", shiftLabel: "Ν", shiftLatex: "N ", displayLatex: "\\nu", shiftDisplayLatex: "N" },
    { label: "ξ", latex: "\\xi ", shiftLabel: "Ξ", shiftLatex: "\\Xi ", displayLatex: "\\xi", shiftDisplayLatex: "\\Xi" },
    { label: "ο", latex: "o ", shiftLabel: "Ο", shiftLatex: "O ", displayLatex: "o", shiftDisplayLatex: "O" },
    { label: "π", latex: "\\pi ", shiftLabel: "Π", shiftLatex: "\\Pi ", displayLatex: "\\pi", shiftDisplayLatex: "\\Pi" },
    { label: "ϖ", latex: "\\varpi ", shiftLabel: "Π", shiftLatex: "\\Pi ", displayLatex: "\\varpi", shiftDisplayLatex: "\\Pi" },
    { label: "ρ", latex: "\\rho ", shiftLabel: "Ρ", shiftLatex: "P ", displayLatex: "\\rho", shiftDisplayLatex: "P" },
    { label: "ϱ", latex: "\\varrho ", shiftLabel: "Ρ", shiftLatex: "P ", displayLatex: "\\varrho", shiftDisplayLatex: "P" },
    { label: "σ", latex: "\\sigma ", shiftLabel: "Σ", shiftLatex: "\\Sigma ", displayLatex: "\\sigma", shiftDisplayLatex: "\\Sigma" },
    { label: "ς", latex: "\\varsigma ", shiftLabel: "Σ", shiftLatex: "\\Sigma ", displayLatex: "\\varsigma", shiftDisplayLatex: "\\Sigma" },
    { label: "τ", latex: "\\tau ", shiftLabel: "Τ", shiftLatex: "T ", displayLatex: "\\tau", shiftDisplayLatex: "T" },
    { label: "υ", latex: "\\upsilon ", shiftLabel: "Υ", shiftLatex: "\\Upsilon ", displayLatex: "\\upsilon", shiftDisplayLatex: "\\Upsilon" },
    { label: "φ", latex: "\\phi ", shiftLabel: "Φ", shiftLatex: "\\Phi ", displayLatex: "\\phi", shiftDisplayLatex: "\\Phi" },
    { label: "ϕ", latex: "\\varphi ", shiftLabel: "Φ", shiftLatex: "\\Phi ", displayLatex: "\\varphi", shiftDisplayLatex: "\\Phi" },
    { label: "χ", latex: "\\chi ", shiftLabel: "Χ", shiftLatex: "X ", displayLatex: "\\chi", shiftDisplayLatex: "X" },
    { label: "ψ", latex: "\\psi ", shiftLabel: "Ψ", shiftLatex: "\\Psi ", displayLatex: "\\psi", shiftDisplayLatex: "\\Psi" },
    { label: "ω", latex: "\\omega ", shiftLabel: "Ω", shiftLatex: "\\Omega ", displayLatex: "\\omega", shiftDisplayLatex: "\\Omega" },
  ],
};
